/**
 * Auto-generate the sidebar from the docs folder structure.
 */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerated sidebars per top‑level section
  walletsSidebar: [{ type: 'autogenerated', dirName: 'wallets' }],
  lokichainSidebar: [{ type: 'autogenerated', dirName: 'lokichain' }],
};

module.exports = sidebars;
